spring:
  datasource:
    username: root
    password: "08052001"
    url: jdbc:mysql://127.0.0.1:3306/knowledge_platform?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: safakochat9@gmail.com
    password: klsc ndrw plxl genv  # App-specific password (from Gmail)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      location: uploads/


  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 20

# Custom app properties
app:

  frontendUrl: http://localhost:5173  # Your Vue dev server URL
  upload-dir: uploads/              # Where uploaded files are stored