spring:
  datasource:
    username: usere
    password: Imbus@2025!
    url: jdbc:mysql://localhost:3306/users
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: "benhassinehabib880@gmail.com"
    password: "abxp ubxh tdub ijgl"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

base:
  url: "http://localhost:8080"
